### ISSUE TITLE
(nvim) CSS properties checklist for Stylus snippets

### ISSUE THREAD

**Issue by shirohana** [shirohana/.config#5]
# Notes

### Didn't snippetted

Property | Description
--- | ---
vertical-align: _length_ | Seems not useful at all?

# Properties

Copied from [w3schools/CSS Reference](https://www.w3schools.com/cssref/).

- [ ] align-content
- [ ] align-items
- [ ] align-self
- [ ] all
- [ ] animation
- [ ] animation-delay
- [ ] animation-direction
- [ ] animation-duration
- [ ] animation-fill-mode
- [ ] animation-iteration-count
- [ ] animation-name
- [ ] animation-play-state
- [ ] animation-timing-function
- [ ] backface-visibility
- [ ] background
- [ ] background-attachment
- [ ] background-blend-mode
- [ ] background-clip
- [ ] background-color
- [ ] background-image
- [ ] background-origin
- [ ] background-position
- [ ] background-repeat
- [ ] background-size
- [x] border
- [x] border-bottom
- [x] border-bottom-color
- [x] border-bottom-left-radius
- [x] border-bottom-right-radius
- [x] border-bottom-style
- [x] border-bottom-width
- [x] border-collapse
- [x] border-color
- [x] border-image
- [x] border-image-outset
- [x] border-image-repeat
- [x] border-image-slice
- [x] border-image-source
- [x] border-image-width
- [x] border-left
- [x] border-left-color
- [x] border-left-style
- [x] border-left-width
- [x] border-radius
- [x] border-right
- [x] border-right-color
- [x] border-right-style
- [x] border-right-width
- [x] border-spacing
- [x] border-style
- [x] border-top
- [x] border-top-color
- [x] border-top-left-radius
- [x] border-top-right-radius
- [x] border-top-style
- [x] border-top-width
- [x] border-width
- [x] bottom
- [ ] box-decoration-break
- [x] box-shadow
- [x] box-sizing
- [ ] caption-side
- [ ] caret-color
- [ ] @charset
- [ ] clear
- [ ] clip
- [x] color
- [ ] column-count
- [ ] column-fill
- [ ] column-gap
- [ ] column-rule
- [ ] column-rule-color
- [ ] column-rule-style
- [ ] column-rule-width
- [ ] column-span
- [ ] column-width
- [ ] columns
- [ ] content
- [ ] counter-increment
- [ ] counter-reset
- [ ] cursor
- [ ] direction
- [x] display
- [ ] empty-cells
- [ ] filter
- [ ] flex
- [ ] flex-basis
- [ ] flex-direction
- [ ] flex-flow
- [ ] flex-grow
- [ ] flex-shrink
- [ ] flex-wrap
- [ ] float
- [ ] font
- [ ] @font-face
- [ ] font-family
- [ ] font-kerning
- [ ] font-size
- [ ] font-size-adjust
- [ ] font-stretch
- [ ] font-style
- [ ] font-variant
- [ ] font-weight
- [ ] grid
- [ ] grid-area
- [ ] grid-auto-columns
- [ ] grid-auto-flow
- [ ] grid-auto-rows
- [ ] grid-column
- [ ] grid-column-end
- [ ] grid-column-gap
- [ ] grid-column-start
- [ ] grid-gap
- [ ] grid-row
- [ ] grid-row-end
- [ ] grid-row-gap
- [ ] grid-row-start
- [ ] grid-template
- [ ] grid-template-areas
- [ ] grid-template-columns
- [ ] grid-template-rows
- [ ] hanging-punctuation
- [x] height
- [ ] hyphens
- [ ] @import
- [ ] isolation
- [ ] justify-content
- [ ] @keyframes
- [x] left
- [x] letter-spacing
- [x] line-height
- [x] list-style
- [x] list-style-image
- [x] list-style-position
- [x] list-style-type
- [x] margin
- [x] margin-bottom
- [x] margin-left
- [x] margin-right
- [x] margin-top
- [ ] max-height
- [ ] max-width
- [ ] @media
- [x] min-height
- [x] min-width
- [ ] object-fit
- [x] opacity
- [ ] order
- [ ] outline
- [ ] outline-color
- [ ] outline-offset
- [ ] outline-style
- [ ] outline-width
- [ ] overflow
- [ ] overflow-x
- [ ] overflow-y
- [x] padding
- [x] padding-bottom
- [x] padding-left
- [x] padding-right
- [x] padding-top
- [ ] page-break-after
- [ ] page-break-before
- [ ] page-break-inside
- [ ] perspective
- [ ] perspective-origin
- [ ] pointer-events
- [x] position
- [ ] quotes
- [ ] resize
- [x] right
- [ ] tab-size
- [ ] table-layout
- [x] text-align
- [x] text-align-last
- [x] text-decoration
- [x] text-decoration-color
- [x] text-decoration-line
- [x] text-decoration-style
- [ ] text-indent
- [ ] text-justify
- [ ] text-overflow
- [ ] text-shadow
- [ ] text-transform
- [x] top
- [ ] transform
- [ ] transform-origin
- [ ] transform-style
- [ ] transition
- [ ] transition-delay
- [ ] transition-duration
- [ ] transition-property
- [ ] transition-timing-function
- [ ] unicode-bidi
- [ ] user-select
- [x] vertical-align
- [ ] visibility
- [x] white-space
- [x] width
- [x] word-break
- [x] word-spacing
- [x] word-wrap
- [ ] z-index
